### ISSUE TITLE
Add Support for Repeating Projects

### ISSUE THREAD

**Issue by timstringer** [ksalzke/defer-this-instance-omnifocus-plugin#2]
It would be helpful if Defer This Instance also worked for repeating projects. As far as I can tell, it currently only works for actions and action groups. Thanks, Kaitlin!

**Comment by ksalzke** [comment]
A sensible suggestion now implemented, thanks Tim. :-)

**Comment by timstringer** [comment]
Thanks very much, Kaitlin!
